---
all:
  hosts:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/ansible_tasks
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: yes
  children:
    builder:
      hosts:
        13.49.104.147:
    webserver:
     hosts:
        13.48.228.164: